name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
